### ISSUE TITLE
vue中出现错误提示无法正常使用

### ISSUE THREAD

**Issue by 95Jialinli** [Chakroun-Anas/turbo-console-log#105]
Cannot read property 'trim' of undefined

**Comment by paulvonber** [comment]
Same, it looks like it broke away after latest vscode update "Version: 1.51.0"

**Comment by Chakroun-Anas** [comment]
Hello,

The problem has nothing to do with the latest version of vscode, in fact the trim function is used in the method that extract  the class name from a line code that contains a class declaration but after a quick check it turns out that they were some edge cases that were not handled.

I just pushed a new version that deal with this: 2.0.3, please update the extension, test again and get back to me.

Thanks.

**Comment by Chakroun-Anas** [comment]
See https://github.com/Chakroun-Anas/turbo-console-log/issues/106

**Comment by 95Jialinli** [comment]
今天插件更新后已经可以正常使用了
