### ISSUE TITLE
ctrl alt L not working : Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by PeterLAxakon** [Chakroun-Anas/turbo-console-log#106]
**Turbo console log stopped working**
getting error:  _Cannot read property 'trim' of undefined_

**Windows** 10 64bit Version: 10.0.19041 build 19041  
**VS Code** Version: 1.51.0 
**Code** Typescript

**Comment by Chakroun-Anas** [comment]
Same as https://github.com/Chakroun-Anas/turbo-console-log/issues/105

**Comment by Chakroun-Anas** [comment]
Hello,

The problem has nothing to do with the latest version of vscode, in fact the trim function is used in the method that extract the class name from a line code that contains a class declaration but after a quick check it turns out that they were some edge cases that were not handled.

I just pushed a new version that deal with this: 2.0.3, please update the extension, test again and get back to me.

Thanks.

**Comment by paulvonber** [comment]
@Chakroun-Anas seems everything is be back on track and working as expected. 
Many thanks for the update!

**Comment by Chakroun-Anas** [comment]
@paulvonber Glad to hear that, you welcome :)
