### ISSUE TITLE
Shift+Alt+D. cannot correctly delete everything printed by Ctrl+Alt+L.

### ISSUE THREAD

**Issue by moYxb** [Chakroun-Anas/turbo-console-log#115]
console.log(`🚀 ~ data`, data);
It can be deleted normally.

console.log(`🚀 ~ this.data`, this.data);
This cannot be removed properly by Shift+Alt+D.

They're all output by Ctrl+Alt+L.

**Comment by AnglusWang** [comment]
I also encountered the same problem

**Comment by liuning0406** [comment]
This may be because configurations such as single and double quotation marks and semicolons at the end of lines are different from your own formatting configuration ；
![image](https://user-images.githubusercontent.com/74040803/173516022-dbd8de6c-00c3-4a5d-a812-336ee722b5a2.png)
![image](https://user-images.githubusercontent.com/74040803/173516077-5bdc3c4f-09fb-43d3-983b-a866fd5e93e9.png)
![image](https://user-images.githubusercontent.com/74040803/173516243-dcfb8faa-365e-4856-bb6a-e418c40599a8.png)

**Comment by Chakroun-Anas** [comment]
Hello,

Not relevant anymore, tested on version `v2.8.0`.

Thank you for reporting the issue.
