### ISSUE TITLE
Wrong log position

### ISSUE THREAD

**Issue by demedos** [Chakroun-Anas/turbo-console-log#135]
Hi,

it's been a while since TCL started placing the logs in the wrong position, sometimes even dozens of lines below the cursor.

Those are my vscode settings:
```JSON
{
  "turboConsoleLog.logMessagePrefix": "TCL:",
  "turboConsoleLog.insertEnclosingFunction": true,
  "turboConsoleLog.includeFileNameAndLineNum": false,
  "turboConsoleLog.insertEnclosingClass": false,
  "turboConsoleLog.delimiterInsideMessage": "",
  "javascript.validate.enable": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.tabSize": 2,
  "editor.formatOnSave": true
}
```

**Comment by AEsmerio** [comment]
I've same issue. I thought it would be because I don't use Semicolons, but that's the issue.

**Comment by yonifra** [comment]
I experience this same behavior. Please fix, it sometimes adds the `console.log` in a very weird place, causing builds to fail later on since I didn't even know there was a console.log there...

**Comment by thebhaskara** [comment]
Facing same issue... is there even a work around?

**Comment by MiniMarker** [comment]
+1 Same issue here

**Comment by Chakroun-Anas** [comment]
Hello guys,

Sorry about the inconveniences, the extension is not perfect, there is no magic solution to make sure that it will function perfectly in every use case, the only thing that we can do is to identify every edge case scenario, report it and fix it, i encourage you to share with the information about each scenario so that we deal with it (code snippet, configurations, etc), thx.

**Comment by demedos** [comment]
@Chakroun-Anas I've been using this extension for years and it's very good, no need to be sorry about anything.
The next time I face this issue I'll try to isolate it and report it back.
