### ISSUE TITLE
closing brace issue 'ㅅ')/

### ISSUE THREAD

**Issue by dragmove** [Chakroun-Anas/turbo-console-log#38]
Hi. I've been using this extension since last week.
Thanks for your fantastic extension. 'ㅅ')/

I discovered this issue on vscode today.
// windows 7. vscode version is 1.30.2.

For example, 
I tried to select 'error' text and run 'Display Log Message' feature using keyboard shortcut.

```javascript
try {
  ...
} catch(error) { // I selected this 'error' parameter and run 'Display Log Message'.
  console.log('TCL: }catch -> error', error) // I think that this closing brace is issue.
}
```

**Comment by Chakroun-Anas** [comment]
Hello,

The catch statement is one of the javascript statements, the extension should look for the function that enclose the try catch block just like it does with if, switch, while and for statements.

I have pushed an update so that the extension behaves as it should be.

Thank you so much for your feedback.
