### ISSUE TITLE
Wonderful extension, but latest version is not working

### ISSUE THREAD

**Issue by m-venkat** [Chakroun-Anas/turbo-console-log#53]
On Windows 10 machine, with latest version of VSCODE and with latest version of extension is not working.  I had to pick the earlier version to make it work. Tried straight forward scenario to create console.log from a variable

**Comment by Chakroun-Anas** [comment]
Hello,

I have just tested the extension with the following setup and it's working perfectly fine:

- Visual Studio Code: 1.32.3 (latest)
- Windows: 10.0.17143

Thank you very much for trying to help in order to make the extension better but as you know if i can't reproduce the issue in a similar environment that you are referring  to it's not a global issue and hence will be closed.
